name: StopTimer
version: ${project.version}
main: me.xydesu.stoptimer.Main
api-version: '1.13'
folia-supported: true
authors: [xydesu]
depend: [PlaceholderAPI]
softdepend: [DiscordSRV]
commands:
  stopserver:
    description: Stops the server and displays the time taken to stop.
    usage: /<command>